name: OreFree Scraper
description: Login to OreFree and scrape current hours
version: 0.0.12
slug: ore_free_scraper
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  8000/tcp: 8000
options:
  port: 8000
  log_level: info
schema:
  port: int(1001,65535)
  log_level: list(trace|debug|info|warn|error|fatal)?
